
#gem set tools leveling config
["tool leveling"]
	#sets whether gem set tools gain perks from levels
	isToolLevelingEnabled = true

	["tool leveling"."leveling config"]
		swordKillsPerLevel = 10
		pickaxeOresPerLevel = 10
		pickaxeBlocksPerLevel = 20
		axeKillsPerLevel = 10
		axeLogsPerLevel = 10
		axeBlocksPerLevel = 20
		shovelBlocksPerLevel = 50
		hoeHoesPerLevel = 50
		hoeCropsPerLevel = 20

#whether minor gems spawn in unique biomes
["gem unique biome generation"]
	#sets whether minor gems spawn uniquely in specific biomes.Disable to make enabled gems generate in every overworld biome
	isUniqueBiomeGenerationEnabled = true

#overworld world generation config
["overworld generation"]
	opal_OreGenEnabled = true
	tanzanite_OreGenEnabled = false
	sapphire_OreGenEnabled = true
	citrine_OreGenEnabled = true
	ametrine_OreGenEnabled = false
	morganite_OreGenEnabled = true
	kunzite_OreGenEnabled = true
	garnet_OreGenEnabled = true
	peridot_OreGenEnabled = true
	tourmaline_OreGenEnabled = true
	blackOpal_OreGenEnabled = false
	ruby_OreGenEnabled = true
	aquamarine_OreGenEnabled = true
	amethyst_OreGenEnabled = false
	topaz_OreGenEnabled = true
	spinel_OreGenEnabled = true
	iolite_OreGenEnabled = false
	zircon_OreGenEnabled = false
	#sets whether mod emerald ore generation is enabled
	emerald_OreGenEnabled = false
	alexandrite_OreGenEnabled = true
	silver_OreGenEnabled = false

["nether generation"]
	kunzite_NetherOreGenEnabled = false
	zircon_NetherOreGenEnabled = true
	tanzanite_NetherOreGenEnabled = true
	citrine_NetherOreGenEnabled = false
	morganite_NetherOreGenEnabled = false
	spinel_NetherOreGenEnabled = false
	sapphire_NetherOreGenEnabled = false
	ruby_NetherOreGenEnabled = false
	diamond_NetherOreGenEnabled = false
	peridot_NetherOreGenEnabled = false
	garnet_NetherOreGenEnabled = false
	#sets whether vanilla emerald ore nether generation is enabled
	v_emerald_NetherOreGenEnabled = false
	ametrine_NetherOreGenEnabled = false
	tourmaline_NetherOreGenEnabled = false
	iolite_NetherOreGenEnabled = true
	amethyst_NetherOreGenEnabled = true
	aquamarine_NetherOreGenEnabled = false
	#sets whether mod emerald ore nether generation is enabled
	emerald_NetherOreGenEnabled = false
	topaz_NetherOreGenEnabled = false
	alexandrite_NetherOreGenEnabled = false
	blackOpal_NetherOreGenEnabled = true
	opal_NetherOreGenEnabled = false

#whether mod loot spawns in chests
["loot spawning"]
	isLootSpawnEnabled = true

